
name: Publish Documentation
on:
  push:
  pull_request:
      branches:
      - main
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Documentation
        shell: bash
        run: |
          ls
          sudo chmod +x getdocs.sh 
          sudo chmod +x doxygen/doxybook2
          sudo ./getdocs.sh
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: docs.derangedsenators.me
          CONFIG_FILE: mkdocs.yml
          EXTRA_PACKAGES: build-base
                          awesome-pages
          # GITHUB_DOMAIN: github.myenterprise.com          
